@startuml
title <size:24>Container View: WEBシステム</size>

set separator none
left to right direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(ユーザー, "ユーザー", $descr="ブラウザを通じてシステムを利用", $tags="", $link="")

System_Boundary("WEBシステム_boundary", "WEBシステム", $tags="") {
  AddBoundaryTag("WEBサーバー", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_1, "WEBサーバー", $tags="WEBサーバー") {
    Container(WEBシステム.バックエンド, "バックエンド", $techn="SpringBoot", $descr="ビジネスロジックの実行とJSONデータ提供", $tags="", $link="")
    Container(WEBシステム.データベース, "データベース", $techn="RDBMS", $descr="データの永続化", $tags="", $link="")
  }

  AddBoundaryTag("クライアント(ブラウザ)", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_2, "クライアント(ブラウザ)", $tags="クライアント(ブラウザ)") {
    Container(WEBシステム.フロントエンド, "フロントエンド", $techn="Reactなど", $descr="ユーザー操作の制御と画面の構築", $tags="", $link="")
  }

}

Rel(WEBシステム.フロントエンド, WEBシステム.バックエンド, "API呼び出し", $techn="HTTP/JSON", $tags="", $link="")
Rel(WEBシステム.バックエンド, WEBシステム.データベース, "JDBC/SQL", $techn="", $tags="", $link="")
Rel(ユーザー, WEBシステム.フロントエンド, "画面操作", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml